apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audiomuse-ai.fullname" . }}-jellyfin
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "audiomuse-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  user_id: {{ .Values.jellyfin.userId | quote }}
  api_token: {{ .Values.jellyfin.token | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audiomuse-ai.fullname" . }}-postgres
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "audiomuse-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audiomuse-ai.fullname" . }}-gemini
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "audiomuse-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  GEMINI_API_KEY: {{ .Values.gemini.apiKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audiomuse-ai.fullname" . }}-ai-chat-db
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "audiomuse-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  AI_CHAT_DB_USER_PASSWORD: {{ .Values.postgres.aiChatDbUserPassword | quote }}